### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by leardilap** [pointhi/kicad-color-schemes#1]
Hi, I love your effort here, would you please add a simple how to install section to the README ? 
I've been trying to find out where should I put the lines that declare the colors but could not do it. 
Many thanks!!

**Comment by pointhi** [comment]
On linux you need to edit ```~/.config/kicad/eeschema```. No idea where this file is located on win/mac

**Comment by wrongPaul** [comment]
on mac the file is located in ~/Library/Preferences/kicad

on windows the file is in C: > Users > ... > AppData > Roaming > kicad

beware that the files themselves aren't generated until you actually close the project manager and all programs completely! this was my problem and why I couldn't find the file, I had just made a fresh install and they simply didn't exist yet

**Comment by pointhi** [comment]
should be fixed by #2 now
